FROM python:3.11-slim

WORKDIR /app

# Zainstaluj UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Skopiuj pliki projektu
COPY pyproject.toml uv.lock ./

# Zainstaluj zależności
RUN uv sync --frozen --no-dev

# Skopiuj kod agenta
COPY . .

# Port
ENV PORT=8080
EXPOSE 8080

# Uruchom ADK
CMD ["uv", "run", "adk", "web", "--host", "0.0.0.0", "--port", "8080","--trace_to_cloud"]